apiVersion: apps/v1
kind: Deployment
metadata:
  name: xlr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: xlr
  template:
    metadata:
      labels:
        app: xlr
    spec:
      containers:
      - image: xebialabs/xl-release:23.1.0
        name: xlr
        ports:
        - containerPort: 8080
        env:
          - name: "ACCEPT_EULA"
            value: "Y"
          - name: "ADMIN_PASSWORD"
            value: "giladmin"
          - name: "XL_LICENSE"
            value: "LS0tIExpY2Vuc2UgLS0tDQpMaWNlbnNlIHZlcnNpb246IDMNClByb2R1Y3Q6IFhMIERlcGxveQ0KTGljZW5zZWQgdG86IFhlYmlhTGFicw0KQ29udGFjdDogWGViaWFMYWJzIEludGVybmFsIFVzZSBPbmx5IDxpbmZvQHhlYmlhbGFicy5jb20+DQpFeHBpcmVzIGFmdGVyOiAyMDM3LTAxLTAxDQpMaWNlbnNlZCBudW1iZXIgb2YgQ0lzOiB4bC5TYXRlbGxpdGU9MTAwMA0KTGljZW5zZWQgcGx1Z2luOiBqYm9zc2FzLXBsdWdpbg0KTGljZW5zZWQgcGx1Z2luOiB3bXEtcGx1Z2luDQpMaWNlbnNlZCBwbHVnaW46IG9zYi1wbHVnaW4NCkxpY2Vuc2VkIHBsdWdpbjogdG9tY2F0LXBsdWdpbg0KTGljZW5zZWQgcGx1Z2luOiB3cHMtcGx1Z2luDQpMaWNlbnNlZCBwbHVnaW46IHdpbmRvd3MtcGx1Z2luDQpMaWNlbnNlZCBwbHVnaW46IGlpcy1wbHVnaW4NCkxpY2Vuc2VkIHBsdWdpbjogYml6dGFsay1wbHVnaW4NCkxpY2Vuc2VkIHBsdWdpbjogd2xzLXBsdWdpbg0KTGljZW5zZWQgcGx1Z2luOiB3YXMtcGx1Z2luDQpMaWNlbnNlZCBwbHVnaW46IGdsYXNzZmlzaC1wbHVnaW4NCkxpY2Vuc2VkIHBsdWdpbjogamJvc3NkbS1wbHVnaW4NClN1cHBvcnQgcG9saWN5OiA4eDUNCkVkaXRpb246IEVudGVycHJpc2UNCi0tLSBTaWduYXR1cmUgKFNIQTF3aXRoRFNBKSAtLS0NCjMwMmMwMjE0MzU4N2U4YTQwNGQ0MjMyYmQ0N2U2OTY1OTI3ODE3MzYyMWFkYjEzNTAyMTQ2NmNlNWExZGZkOTYxYmZhNDQ4OGY0ZTJmMDM2DQpiYTMzODkwZTY3ZWINCi0tLSBFbmQgb2YgU2lnbmF0dXJlIC0tLQ=="