# Exported from:        http://Gilbert-Guadana:5516/
# Release version:      24.3.6
# Date created:         Tue Apr 22 14:19:23 MDT 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
